version: "3.4"

services:
    database_desafios:
        image: postgres
        container_name: database_desafios
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=fin_api
        volumes: 
            - pgdata_desafios:/data/postgres
        network_mode: host

volumes: 
    pgdata_desafios:
        driver: local